Colorize perf leaks
luxteam/jobs_launcher pull request #104
Opened 2020-10-16 15:53 UTC by Kataderon

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1673

## PURPOSE
* Colorize group if it has cases with performance leak
* Colorize cases with performance leak

## REPORTS

2020-10-20 07:34 UTC, Piromancer commented
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3913/Test_20Report/
Почему здесь упали тесты?

2020-10-20 09:36 UTC, Kataderon commented
> https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3913/Test_20Report/
> Почему здесь упали тесты?

Мак завис, логов нет. Мой пр вообще не трогает тестовую стадию

2020-10-20 13:57 UTC, Piromancer requested changes
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3917/Test_20Report/
Покрасило все группы, хотя не везде просадки.

2020-10-21 11:12 UTC, Piromancer commented
Красится неправильно, сейчас красится в зависимости от разницы по процентам, а по алгоритму должно сравниваться с простой разницей между временем бейзлайна и ренедр тайма

2020-10-21 14:01 UTC, Piromancer submitted a review, later dismissed

2020-10-21 17:42 UTC, epozine commented
Реши конфликт пожалуйста

2020-10-27 10:15 UTC, epozine approved these changes

2020-10-27 11:35 UTC, Speedwag00n approved these changes

2020-10-27 11:35 UTC, merged