Add column with build name
luxteam/jobs_launcher pull request #151
Opened 2020-12-29 14:58 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-2034
### Purpose
* Set build name (without priority) as env variable for use it in jobs_launcher during report building
### :octocat: Related PR'S
* rpr_pipelines: 
### Jenkins Builds
* Blender (without special name): https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3334/Test_20Report/
* Blender (with some name): https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3333/Test_20Report/

2020-12-29 20:04 UTC, Piromancer requested changes
Можешь, пожалуйста, сделать её первой колонкой? В остальном все хорошо, спасибо

2020-12-30 06:51 UTC, epozine approved these changes

2020-12-30 08:23 UTC, Speedwag00n commented
Готово

2020-12-30 09:51 UTC, epozine approved these changes

2020-12-30 10:00 UTC, merged