Refactor for max and rprviewer case names
luxteam/jobs_launcher pull request #152
Opened 2020-12-30 02:33 UTC by Flame0n

### **Jira Ticket** 

- https://adc.luxoft.com/jira/browse/STVCIS-1760
- https://adc.luxoft.com/jira/browse/STVCIS-1759

### **Purpose**

- Change the name of files and fields

### **Effect of change**

- After changes, the tests and their contents will be more similar to the rest of the jobs.

### **Jenkins Builds**

- https://rpr.cis.luxoft.com/job/RadeonProViewerManual/959/

2020-12-30 07:21 UTC, Speedwag00n requested changes
Билды еще не видел, но уверен, что в Максе будет сломана отправка данных в UMS по следующей причине:
Во всех тулах, кроме Макса, описание кейсов по структуре это массив json объектов, описывающих каждый свой кейс 
https://github.com/luxteam/jobs_test_blender/blob/master/jobs/Tests/AOV/test_cases.json#L1
В Максе это уровень вложенности другой (массив объектов кейсов не в корне файла, а по ключу cases)
https://github.com/luxteam/jobs_test_max/blob/master/jobs/Tests/AOV/case_list.json#L3

Лучшим вариантом будет в Максе изменить уровень вложенности (удалить ключи test_group и cases, содержимое cases поместить в корень файлов). Тогда получатся файлы по аналогии с остальными тулами

2020-12-30 09:47 UTC, Flame0n commented
Изменил max билд на этот - https://rpr.cis.luxoft.com/job/RadeonProRenderMaxPluginManual/1102/

2021-01-11 10:39 UTC, Flame0n commented
Удалил все изменения для Max, чтобы завести их отдельно.

2021-01-11 15:32 UTC, Speedwag00n approved these changes

2021-01-12 10:46 UTC, merged