Add python script into local reports
luxteam/jobs_launcher pull request #153
Opened 2021-01-12 07:20 UTC by Flame0n

### **Jira Ticket** 

- https://adc.luxoft.com/jira/browse/STVCIS-1797

### **Purpose**

- Add "functions" column into templates from test_cases.json

### **Jenkins Builds**

- https://rpr.cis.luxoft.com/job/RadeonProViewerManual/968/
- https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3410/
- https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4263/

2021-01-12 09:38 UTC, Speedwag00n approved these changes
С точки зрения кода все хорошо.
Скорее всего нужно будет поменять оформление содержимого колонки, чтобы проще читалось, но это уже решит @Piromancer

2021-01-12 09:52 UTC, Piromancer requested changes
В таком виде это не юзаемо, можешь, пожалуйста, парсить строчки? Например, если в json-е написано так:
'functions': [
"if not cmds.pluginInfo('fbxmaya', query=True, loaded=True): cmds.loadPlugin('fbxmaya', quiet=True)",
'mel.eval(/'FBXImport -f ("/' + RES_PATH + /'" + "/Smoke/default/park_bench1.fbx")/')',
'rpr_render(case)',
"cmds.delete('Default')"
]

то в поле должно быть
if not cmds.pluginInfo('fbxmaya', query=True, loaded=True): cmds.loadPlugin('fbxmaya', quiet=True)
mel.eval(/'FBXImport -f ("/' + RES_PATH + /'" + "/Smoke/default/park_bench1.fbx")/')
rpr_render(case)
cmds.delete('Default')

Таким образом можно просто скопировать код в тулу

2021-01-13 09:48 UTC, Flame0n commented
Тесты с измененным форматированием:

- https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/4291/
- https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3436/

2021-01-13 10:39 UTC, Piromancer commented
В блендере все еще нет переноса строк

2021-01-13 12:45 UTC, Flame0n commented
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3464/

2021-01-13 12:48 UTC, Piromancer approved these changes

2021-01-13 14:30 UTC, epozine approved these changes

2021-01-13 14:30 UTC, merged