Max refactor groups
luxteam/jobs_launcher pull request #170
Opened 2021-03-10 16:37 UTC by Flame0n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1759
### Purpose
* Refactoring the code to be more consistent with the other jobs
### Related PR'S
* 
### Jenkins Builds
* Max master: https://rpr.cis.luxoft.com/job/RadeonProRenderMaxPluginManual/1142/
* Max refactor: https://rpr.cis.luxoft.com/job/RadeonProRenderMaxPluginManual/1144/

2021-03-26 13:18 UTC, Speedwag00n submitted a review, later dismissed

2021-03-27 13:15 UTC, epozine requested changes

2021-03-27 13:15 UTC, epozine commented on common/scripts/utils.py
>      if local_config.tool_name == "max":
Может этот if можно вообще убрать? Мы вроде это хотели
# FIXME: make general implementation after refactoring of Max repository

2021-03-27 13:15 UTC, epozine commented on core/config.py
>  TEST_CASES_JSON_NAME = {
Может это тоже теперь можно убрать? Мы вроде пришли к единому формату

2021-03-27 13:15 UTC, epozine commented on core/config.py
>  TEST_CASES_JSON_NAME = {
@Speedwag00n просьба подсказать Алексею какие моменты можно еще убрать если они есть

2021-03-27 14:23 UTC, Speedwag00n commented on core/config.py
>  TEST_CASES_JSON_NAME = {
Кроме того, что уже убрали/упомянули ничего больше не нашел

2021-03-28 01:06 UTC, Flame0n commented
https://rpr.cis.luxoft.com/job/RadeonProRenderMaxPluginManual/1155/ - Удаление ссылок на старые файлы

2021-04-25 08:20 UTC, Speedwag00n submitted a review, later dismissed

2021-04-27 11:56 UTC, epozine approved these changes

2021-04-27 11:57 UTC, merged

2021-04-27 11:57 UTC, Speedwag00n approved these changes