Stvcis 2441/fix suiteid err in jobs launcher
luxteam/jobs_launcher pull request #204
Opened 2021-07-20 12:31 UTC by testpassword

### Jira Ticket
- https://luxproject.luxoft.com/jira/browse/STVCIS-2441

### Purpose
- Stabilize receiving data from UMS
- Speed ​​up data retrieval from ums

### Effect of change
- If request to UMS throws Error, wait one minute and try again
- Uses new api route witch didn't return unnecessary data

### Jenkins Builds
- https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4986/
- https://ums3.cistest.luxoft.com/products/5f3b1557929d5171e9d25757/60f6a8e1c2ddd15e9076bd75/summary?selected=Emissive_Light&tab=suites

2021-07-22 10:15 UTC, GulDilin approved these changes

2021-07-22 10:18 UTC, GulDilin reviewed
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4986/artifact/AppleM1-OSX-Emissive_Light-FULL2/AppleM1-OSX-Emissive_Light-FULL2_engine_0.log
Здесь видно, что возникла ошибка при декодировании json. Не очень понятно для какого именно ums клиента. Можешь проверить?

2021-07-22 10:22 UTC, GulDilin requested changes
Думаю будет не лишним указать в логе для какого экземпляра был запрос

2021-07-22 12:21 UTC, testpassword commented
Там ошибка для прода возникла, я с этим тоже долго мучался, пока не понял по id билдов.

Различие прода и дев добавлю.

2021-07-22 17:37 UTC, GulDilin approved these changes

2021-07-28 07:41 UTC, epozine approved these changes

2021-08-03 09:57 UTC, merged