Add features to compare/ignore part of image
luxteam/jobs_launcher pull request #434
Opened 2023-06-14 08:32 UTC by Sofshik

https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1577/
Library_Plastic 2nd case
Main_Menu 7th case

2023-06-14 09:12 UTC, Speedwag00n requested changes

2023-06-14 09:12 UTC, Speedwag00n commented on common/scripts/CompareMetrics.py
> +            cv2.imwrite("C:\\Users\\user\\Desktop\\2.png", self.img2)
Похоже на изменения для дебага. Если да, то их нужно удалить

2023-06-14 21:47 UTC, Sofshik commented
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1589/

2023-06-16 06:49 UTC, Speedwag00n requested changes

2023-06-16 06:49 UTC, Speedwag00n commented on common/scripts/CompareMetrics.py
> +                diff_pixels = float(self.diff_pixels / len(diffR.ravel())) * 100
Тут и на строках 87-113 получается блок дублированного кода. Стоит оформить его в отдельную функцию (можно даже внутри функции getDiffPixeles)

2023-06-16 06:49 UTC, Speedwag00n commented on common/scripts/CompareMetrics.py
> +                    return 2
Здесь нужно обновить логику. Будем считать картинку полностью черной, если на всех compare_part она черная. Иначе может быть ситуация. что одна часть полнстью черная, другая - нет

2023-06-16 06:50 UTC, Speedwag00n requested changes

2023-06-16 06:50 UTC, Speedwag00n commented on common/scripts/CompareMetrics.py
> +                    if max(a) <= max_size and median[0][0] != 255:
На строка 125-141 и 165-187 тоже повторящийся код. Его тоже оформить в отдельную функцию

2023-06-18 10:37 UTC, Sofshik commented
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1595/

2023-06-18 12:59 UTC, Speedwag00n approved these changes

2023-06-18 12:59 UTC, merged