add logic for streaming tools overview report building
luxteam/jobs_launcher pull request #459
Opened 2023-10-12 15:36 UTC by mark-rom

2023-10-18 09:46 UTC, Speedwag00n requested changes

2023-10-18 09:46 UTC, Speedwag00n commented on core/reportExporterOverview.py
> +                        test_group_name = test_group.split("_")[-1] if streaming_compare else test_group
Если будет нижнее подчеркивание в название группы, то так не отработает. Нужно отбрасывать только первую часть с нижним подчеркиванием

2023-10-18 10:44 UTC, mark-rom commented on core/reportExporterOverview.py
> +                        test_group_name = test_group.split("_")[-1] if streaming_compare else test_group
Предлагаю решать это использованием названий групп без нижнего подчеркивания (в целом так сейчас и есть, кроме AMDLink), потому что нормального решения без пары ифов строки на 3-5 я не смог придумать(

2023-11-13 13:05 UTC, Speedwag00n approved these changes

2023-11-24 07:13 UTC, merged