sshikalova/max size
luxteam/jobs_launcher pull request #476
Opened 2023-12-05 08:06 UTC by Sofshik

https://rpr.cis.luxoft.com/job/RenderStudio-Manual/2094/

2023-12-05 08:13 UTC, Speedwag00n requested changes

2023-12-05 08:13 UTC, Speedwag00n commented on common/scripts/compareByJSON.py
> +                    img["message"].append(f"Max size: {max_size}")
Лучше сохранить это значение отдельным полем, чтобы оно не отображалось в репорте вместе с сообщением
Если эту информацию когда-нибудь понадобится посмотреть, что маловероятно, можно будет посмотреть в JSON'ы с результатами

2023-12-05 08:16 UTC, Sofshik commented on common/scripts/compareByJSON.py
> +                    img["message"].append(f"Max size: {max_size}")
Это я просто для отладки добавила, планировала удалить перед мерджем

2023-12-11 07:14 UTC, Speedwag00n approved these changes

2023-12-11 07:14 UTC, merged