Add new status column
luxteam/jobs_launcher pull request #70
Opened 2020-08-19 14:26 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1264
### Purpose
* Add new status column that contains a reason why test failed or "passed" depending on test status
### Effect of change
* Collect info about group timeouts
* Mark that testcase was finished when script write info about rendered testcase (for track group timeout exceeded issue)
### Related PR's

### Jenkins Builds
* Blender Tahoe: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2389/Test_20Report/
* Blender Northstar: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2390/Test_20Report/

2020-08-20 15:48 UTC, Kataderon commented on core/reportExporter.py
> +        rc = -1
Лучше тогда сделать свой код возврата для каждого случая и подписать хотя бы в коде

2020-08-20 15:53 UTC, Kataderon approved these changes

2020-08-20 16:28 UTC, Speedwag00n commented on core/reportExporter.py
> +        rc = -1
Доработаю в рамках отдельного ПРа. Создал тикет, чтобы не забыть: https://adc.luxoft.com/jira/browse/STVCIS-1457

2020-08-24 08:35 UTC, Piromancer requested changes
![image](https://user-images.githubusercontent.com/44932328/91021863-06b17080-e5fd-11ea-939e-e632676a33c8.png)
В Difference render time не проценты а секунды.
И лучше переименовать графу в Render time difference

И Pixel difference new лучше переименовать в Pixel difference status

2020-08-24 08:47 UTC, Piromancer commented
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3611/Test_20Report/

2020-08-24 09:48 UTC, Speedwag00n commented
> ![image](https://user-images.githubusercontent.com/44932328/91021863-06b17080-e5fd-11ea-939e-e632676a33c8.png)
> В Difference render time не проценты а секунды.
> И лучше переименовать графу в Render time difference
> 
> И Pixel difference new лучше переименовать в Pixel difference status

Pixel difference status переименовал. Разницу во времени исправил для плагинов. Для коры изменения внесены в этом ПРе: https://github.com/luxteam/jobs_launcher/pull/67
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2472/Test_20Report/NVIDIA_RTX2080TI-Windows-Emissive_Light/Results/Blender28/Emissive_Light/report.html?searchText=BL28_L_EMIS_001

2020-08-25 09:54 UTC, epozine approved these changes

2020-08-25 11:17 UTC, MagisterDemens requested changes
TIMEOUT var

+ Аппрув от QA на изменения в отчете

2020-08-25 11:17 UTC, MagisterDemens commented on core/reportExporter.py
> +        host_name = host_name.replace('-OSX', '')
Почему для macOS указазание ОС удаляется, а для других систем нет?

2020-08-25 11:17 UTC, MagisterDemens commented on core/config.py
> -TIMEOUT = 2400
Почему удалена переменная? Причем не полностью, она используется в [jobs_launcher/jobs_launcher.py](jobs_launcher/jobs_launcher.py)

2020-08-25 11:17 UTC, MagisterDemens commented on core/config.py
> +    "group_timeout_exceeded": True
Значения по-умолчанию корректно заданы?

2020-08-25 11:22 UTC, Speedwag00n commented on core/reportExporter.py
> +        host_name = host_name.replace('-OSX', '')
В названиях машин с виндой и убунту присутствует название ос (в большинстве случаев): Rome-WIN10, Paris-Ubuntu18
Для OSX наоборот: Mumbai, Goto
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8Plugin-WeeklyFull/Test_20Report/

2020-08-25 11:23 UTC, Speedwag00n commented on core/config.py
> -TIMEOUT = 2400
Перенес выше: https://github.com/luxteam/jobs_launcher/blob/32137200ec719952f4eabbdbb67b9417e28453b3/core/config.py#L6
Использовал ее в RENDER_REPORT_BASE до того, как оказалось, что добавлять значение таймаутов для групп в отчет нет необходимости

2020-08-25 11:27 UTC, Speedwag00n commented on core/config.py
> +    "group_timeout_exceeded": True
Да, значение корректные:
Если кейс завершится, он сохраняет вместе с информацией о рендере для поля "group_timeout_exceeded" значение False (соответственно, если кейс не сохранил информацию о себе, то считаем, что произошел таймаут для группы)
"testcase_timeout_exceeded" используется только для вьюера, там он задается для каждого тесткейса в зависимости от того, возникло ли исключение, связанное с таймаутом кейса или нет: https://github.com/luxteam/jobs_test_rprviewer/blob/2d9731b1ba56685f983473bcc3573608a8d4b199/jobs/Scripts/simpleRender.py#L186

2020-08-25 11:36 UTC, MagisterDemens approved these changes

2020-08-25 12:23 UTC, Piromancer approved these changes

2020-08-26 08:15 UTC, Kataderon approved these changes

2020-08-26 11:50 UTC, merged