[STVCIS-1443] Implement black render detection & processing
luxteam/jobs_launcher pull request #81
Opened 2020-09-09 07:23 UTC by MagisterDemens

[STVCIS-1443](https://adc.luxoft.com/jira/browse/STVCIS-1443)

Comparator will return *2* for black render, case will be marked as incorrect result
If black image is expected result, case's attribute **script_info** should contain phrase:
https://github.com/luxteam/jobs_launcher/blob/7df61055e5ef898434cc7e6df25d8c906573911c/core/config.py#L72

⚠️ Autotests update required. @Piromancer

2020-09-09 08:50 UTC, Speedwag00n approved these changes

2020-09-09 08:51 UTC, Kataderon approved these changes

2020-09-10 13:38 UTC, Piromancer approved these changes
Все работает, я напишу когда помечу все тесты
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2692/Test_20Report/

2020-09-10 13:40 UTC, Piromancer commented
Только такое замечание, сейчас помечается Pixel Difference Status как 2, а в Pop-up подсказке не указано, что он означает. Наверное надо по хорошему добавить описание
![image](https://user-images.githubusercontent.com/44932328/92737886-2a5a1200-f384-11ea-9eac-d16bf9d250c1.png)

2020-09-14 10:13 UTC, epozine submitted a review, later dismissed

2020-10-01 10:04 UTC, Piromancer requested changes
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3807/Test_20Report/
Странно, что 001 прошел. Он ведь не помечен. Можешь посмотреть эту ветку? Там ведь все правильно?

2020-10-14 18:58 UTC, merged