Fix baselines issues
luxteam/jobs_launcher pull request #94
Opened 2020-10-02 12:55 UTC by Kataderon

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1646
https://adc.luxoft.com/jira/browse/STVCIS-1611

## PURPOSE
* Fix issues with comparing images
* Replace 'sec' with '%' for time diff
* Fix issue with thumb of baselines

## NOTES FOR REVIEWERS

## REPORTS

2020-10-07 16:19 UTC, epozine commented
Когда ожидается отчет?

2020-10-13 09:23 UTC, Piromancer commented
А для чего использовались другие удаленные скрипты?

2020-10-13 11:32 UTC, Piromancer requested changes
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderMayaPluginManual/3863/Test_20Report/
Тикет https://adc.luxoft.com/jira/browse/STVCIS-1611 не пофикшен

2020-10-14 15:43 UTC, Kataderon commented
> А для чего использовались другие удаленные скрипты?

Для сравнения картинок

2020-10-14 19:06 UTC, epozine approved these changes

2020-10-16 07:46 UTC, Piromancer commented
When baselines are missing for test cases, test case should be considered failed.
Они все еще считаются Passed

2020-10-16 07:47 UTC, Piromancer requested changes
^

2020-10-19 14:34 UTC, Piromancer approved these changes

2020-10-19 14:46 UTC, merged