Handle skipped groups
luxteam/jobs_launcher pull request #96
Opened 2020-10-08 18:01 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1603
### Purpose
* Handle skipped groups
### Effect of change
* Implement script for check skipped groups.
* Modify countLostTests script for check which groups was skipped
### Technical steps
- [x] Call a script which allows to check that group is fully skipped or not
- [x] Skip executing of fully skipped test groups
- [x] Generate number of skipped test suites using countLostTests script
### :warning: Notes for Reviewers
* Tests can be launched by choosing 'inemankov/handle_skipped_groups' as a branch of pipelines repository and 'inemankov/handle_skipped_groups' as a branch of tests repository
### :octocat: Related PR'S
* rpr_pipelines: 
* jobs_test_blender: 
* jobs_test_maya: 
* jobs_test_rprviewer: 
### Jenkins Builds
* Blender: https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/272/
* Maya: https://rpr.cis.luxoft.com/job/DevRadeonProRenderMayaPluginManual/7/
* RprViewer: https://rpr.cis.luxoft.com/job/RadeonProViewerManual/874/

2020-10-13 11:39 UTC, Piromancer requested changes
Уберите, пожалуйста, отображение Time Taken, Render Time, Setup Time у скипнутых групп

2020-10-13 13:18 UTC, Speedwag00n commented
> Уберите, пожалуйста, отображение Time Taken, Render Time, Setup Time у скипнутых групп

Убрал. Также сделал полностью скипнутые группы вьюера не отображаемыми в отчете.
Изменения можно увидеть в прикрепленных отчетах Блендера и Вьюера (они обновлены)

2020-10-15 11:43 UTC, Piromancer approved these changes

2020-10-15 11:45 UTC, epozine approved these changes

2020-10-15 11:45 UTC, epozine commented on core/countLostTests.py
>  			"AMD_WX9100": "Radeon (TM) Pro WX 9100",
Добавь 2070 убунту

2020-10-15 17:20 UTC, merged